//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagement.Exception {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskManagement.Exception.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exists.
        /// </summary>
        public static string EMAIL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid e-mail and/or password.
        /// </summary>
        public static string INVALID_EMAIL_AND_OR_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_EMAIL_AND_OR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tasks were found.
        /// </summary>
        public static string NO_TASKS_WERE_FOUND {
            get {
                return ResourceManager.GetString("NO_TASKS_WERE_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua senha deve ter no mínimo 8 caracteres, contendo pelo menos uma letra maiúscula, uma letra minúscula, um número e um caractere especial(por exemplo, !,?,*, ..
        /// </summary>
        public static string PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pending task limit reached.
        /// </summary>
        public static string PENDING_TASK_LIMIT_RECHEADED {
            get {
                return ResourceManager.GetString("PENDING_TASK_LIMIT_RECHEADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task category with id was not found.
        /// </summary>
        public static string TASK_CATEGORY_WITH_ID_WAS_NOT_FOUND {
            get {
                return ResourceManager.GetString("TASK_CATEGORY_WITH_ID_WAS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task with Id was not found.
        /// </summary>
        public static string TASK_WITH_ID_WAS_NOT_FOUND {
            get {
                return ResourceManager.GetString("TASK_WITH_ID_WAS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date cannot be in the future.
        /// </summary>
        public static string THE_DATE_CANNOT_BE_IN_THE_FUTURE {
            get {
                return ResourceManager.GetString("THE_DATE_CANNOT_BE_IN_THE_FUTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is not in valid format.
        /// </summary>
        public static string THE_EMAIL_IS_NOT_IN_VALID_FORMAT {
            get {
                return ResourceManager.GetString("THE_EMAIL_IS_NOT_IN_VALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is required.
        /// </summary>
        public static string THE_EMAIL_IS_REQUIRED {
            get {
                return ResourceManager.GetString("THE_EMAIL_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is required.
        /// </summary>
        public static string THE_NAME_IS_REQUIRED_ {
            get {
                return ResourceManager.GetString("THE_NAME_IS_REQUIRED ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task type must be a valid enum value.
        /// </summary>
        public static string THE_TASK_TYPE_MUST_BE_A_VALID_ENUM_VALUE {
            get {
                return ResourceManager.GetString("THE_TASK_TYPE_MUST_BE_A_VALID_ENUM_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title is required.
        /// </summary>
        public static string THE_TITLE_IS_REQUIRED {
            get {
                return ResourceManager.GetString("THE_TITLE_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow error.
        /// </summary>
        public static string UNKNOW_ERROR {
            get {
                return ResourceManager.GetString("UNKNOW_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with Id not was found.
        /// </summary>
        public static string USER_WITH_ID_NOT_WAS_FOUND {
            get {
                return ResourceManager.GetString("USER_WITH_ID_NOT_WAS_FOUND", resourceCulture);
            }
        }
    }
}
